/*
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * An HTTP server that serves a complete DNG file generated by libcamera's
 * own DNGWriter. Also provides video control and reset endpoints.
 *
 * Copyright (C) 2025 Yasin Tunçer
 */

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>   /* strncasecmp */
#include <sys/socket.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

#include "config.h"
#include "capture.h"
#include "capture_controls.h"
#include "still-source.h"
#include "video-source.h"

#ifdef HAVE_LIBCAMERA
// libcamera C++ interface
extern struct still_source *libcamera_get_still_source(struct video_source *s);
extern void libcamera_still_source_set_callback(struct still_source *ssrc,
                                                void (*cb)(void *, struct still_buffer *),
                                                void *data);
extern int libcamera_apply_video_controls(struct video_source *s,
                                           const capture_controls_t *cc);
extern int libcamera_reset_controls(struct video_source *s);
#endif

// Forward declarations
static void *client_thread_func(void *arg);
static void *http_server_thread(void *arg);
static void still_capture_ready_cb(void *data, struct still_buffer *buffer);

/* ─────────────────────────────────────────────────────────────────────────
 * find_query_param()
 *
 * HTTP isteğinin request line'ından (ör. "GET /capture?gain=2.0&awb=cloudy HTTP/1.1")
 * istenen parametreyi bulur ve değerinin başına işaret eden pointer döndürür.
 * Bulunamazsa NULL.
 * ───────────────────────────────────────────────────────────────────────── */
static const char *find_query_param(const char *request_line, const char *key)
{
    const char *qs = strchr(request_line, '?');
    if (!qs) return NULL;
    qs++;  /* '?' sonrası */

    size_t klen = strlen(key);
    const char *p = qs;

    while (*p && *p != ' ' && *p != '\r' && *p != '\n') {
        /* Her parametre 'key=value' biçimindedir; '&' ile ayrılır */
        if (strncasecmp(p, key, klen) == 0 && p[klen] == '=') {
            return p + klen + 1;  /* değerin başı */
        }
        /* Sonraki '&'ye atla */
        const char *amp = strchr(p, '&');
        if (!amp) break;
        p = amp + 1;
    }
    return NULL;
}

/* ─────────────────────────────────────────────────────────────────────────
 * parse_controls_from_request()
 *
 * HTTP request line'ından capture_controls_t doldurur.
 * Desteklenen parametreler:
 *
 *   exposure=<us>          0 veya yok → AE otomatik
 *   gain=<float>           0 veya yok → AG otomatik
 *   awb=auto|incandescent|tungsten|fluorescent|indoor|daylight|cloudy|custom|manual
 *   colour_gain_r=<float>  (awb=manual ile birlikte)
 *   colour_gain_b=<float>  (awb=manual ile birlikte)
 *   brightness=<-100..100> 0 nötr, yok → değiştirilmez
 *   contrast=<0..100>      50 = varsayılan (1.0), yok → değiştirilmez
 *   saturation=<0..100>    50 = varsayılan (1.0), yok → değiştirilmez
 *   sharpness=<0..100>     50 = varsayılan (1.0), yok → değiştirilmez
 * ───────────────────────────────────────────────────────────────────────── */
static capture_controls_t parse_controls_from_request(const char *request_line)
{
    capture_controls_t cc = capture_controls_default();
    const char *v;

    /* exposure */
    v = find_query_param(request_line, "exposure");
    if (v) {
        long us = strtol(v, NULL, 10);
        cc.exposure_us = (us > 0) ? (int64_t)us : 0;
    }

    /* gain — "gain=" ≠ "colour_gain_r=" (tam anahtar eşleşmesi) */
    v = find_query_param(request_line, "gain");
    if (v) {
        float g = strtof(v, NULL);
        cc.gain = (g > 0.0f) ? g : 0.0f;
    }

    /* awb modu */
    v = find_query_param(request_line, "awb");
    if (v) {
        if      (strncasecmp(v, "incandescent", 12) == 0) cc.awb_mode = AWB_INCANDESCENT;
        else if (strncasecmp(v, "tungsten",      8) == 0) cc.awb_mode = AWB_TUNGSTEN;
        else if (strncasecmp(v, "fluorescent",  11) == 0) cc.awb_mode = AWB_FLUORESCENT;
        else if (strncasecmp(v, "indoor",        6) == 0) cc.awb_mode = AWB_INDOOR;
        else if (strncasecmp(v, "daylight",      8) == 0) cc.awb_mode = AWB_DAYLIGHT;
        else if (strncasecmp(v, "cloudy",        6) == 0) cc.awb_mode = AWB_CLOUDY;
        else if (strncasecmp(v, "custom",        6) == 0) cc.awb_mode = AWB_CUSTOM;
        else if (strncasecmp(v, "manual",        6) == 0) cc.awb_mode = AWB_MANUAL;
        else                                               cc.awb_mode = AWB_AUTO;
    }

    /* colour gains (yalnızca awb=manual ile anlamlı) */
    v = find_query_param(request_line, "colour_gain_r");
    if (v) cc.colour_gain_r = strtof(v, NULL);

    v = find_query_param(request_line, "colour_gain_b");
    if (v) cc.colour_gain_b = strtof(v, NULL);

    /* brightness: -100 … +100 */
    v = find_query_param(request_line, "brightness");
    if (v) {
        int bv = (int)strtol(v, NULL, 10);
        cc.brightness = (bv < -100) ? -100 : (bv > 100) ? 100 : bv;
    }

    /* contrast: 0 … 100 */
    v = find_query_param(request_line, "contrast");
    if (v) {
        int cv = (int)strtol(v, NULL, 10);
        cc.contrast = (cv < 0) ? 0 : (cv > 100) ? 100 : cv;
    }

    /* saturation: 0 … 100 */
    v = find_query_param(request_line, "saturation");
    if (v) {
        int sv = (int)strtol(v, NULL, 10);
        cc.saturation = (sv < 0) ? 0 : (sv > 100) ? 100 : sv;
    }

    /* sharpness: 0 … 100 */
    v = find_query_param(request_line, "sharpness");
    if (v) {
        int shv = (int)strtol(v, NULL, 10);
        cc.sharpness = (shv < 0) ? 0 : (shv > 100) ? 100 : shv;
    }

    return cc;
}


// Callback to receive the final DNG data from the C++ side.
static void still_capture_ready_cb(void *data, struct still_buffer *buffer_from_camera) {
    struct http_client_session *session = (struct http_client_session *)data;

    pthread_mutex_lock(&session->mtx);
    session->captured_data.mem = NULL;
    session->captured_data.error = true;

    if (buffer_from_camera && !buffer_from_camera->error && buffer_from_camera->mem && buffer_from_camera->bytesused > 0) {
        session->captured_data.mem = malloc(buffer_from_camera->bytesused);
        if (session->captured_data.mem) {
            memcpy(session->captured_data.mem, buffer_from_camera->mem, buffer_from_camera->bytesused);

            session->captured_data.bytesused = buffer_from_camera->bytesused;
            session->captured_data.timestamp = buffer_from_camera->timestamp;
            session->captured_data.error = false;
        } else {
            fprintf(stderr, "Failed to allocate memory for client DNG buffer\n");
        }
    }

    session->capture_complete = true;
    pthread_cond_signal(&session->cond);
    pthread_mutex_unlock(&session->mtx);
}

/* ─────────────────────────────────────────────────────────────────────────
 * send_json_response() — yardımcı: basit JSON yanıt gönder
 * ───────────────────────────────────────────────────────────────────────── */
static void send_json_response(int fd, int status_code, const char *status_text,
                                const char *json_body)
{
    char header[512];
    int body_len = (int)strlen(json_body);
    int hlen = snprintf(header, sizeof(header),
                        "HTTP/1.1 %d %s\r\n"
                        "Content-Type: application/json\r\n"
                        "Access-Control-Allow-Origin: *\r\n"
                        "Access-Control-Allow-Methods: GET, OPTIONS\r\n"
                        "Content-Length: %d\r\n\r\n",
                        status_code, status_text, body_len);
    write(fd, header, hlen);
    write(fd, json_body, body_len);
}

static void *client_thread_func(void *arg) {
    struct http_client_session *session = (struct http_client_session *)arg;
    char request_buf[2048] = {0};

    if (read(session->fd, request_buf, sizeof(request_buf) - 1) <= 0) {
        goto cleanup;
    }

    /* ─── /capture endpoint ─── */
    if (strstr(request_buf, "GET /capture") == request_buf) {
        if (!session->server->still_src) {
            const char *response = "HTTP/1.1 503 Service Unavailable\r\n"
                              "Access-Control-Allow-Origin: *\r\n"
                              "Access-Control-Allow-Methods: GET, OPTIONS\r\n"
                              "\r\n";
            write(session->fd, response, strlen(response));
        } else {
#ifdef HAVE_LIBCAMERA
            capture_controls_t cc = parse_controls_from_request(request_buf);

            if (cc.exposure_us > 0) {
                fprintf(stdout, "HTTP capture: Manual exposure: %lld us\n", (long long)cc.exposure_us);
            }
            if (cc.gain > 0.0f) {
                fprintf(stdout, "HTTP capture: Manual gain: %.2f\n", cc.gain);
            }
            if (cc.awb_mode != AWB_AUTO) {
                fprintf(stdout, "HTTP capture: AWB mode: %d\n", cc.awb_mode);
            }

            libcamera_still_source_set_callback(session->server->still_src, still_capture_ready_cb, session);

            if (still_source_capture(session->server->still_src, &cc) < 0) {
                const char *response = "HTTP/1.1 500 Internal Server Error\r\n\r\nCapture trigger failed";
                write(session->fd, response, strlen(response));
            } else {
                pthread_mutex_lock(&session->mtx);
                while (!session->capture_complete) {
                    pthread_cond_wait(&session->cond, &session->mtx);
                }
                
                if (session->captured_data.mem && !session->captured_data.error) {
                    char http_header[512];
                    int len = snprintf(http_header, sizeof(http_header),
                              "HTTP/1.1 200 OK\r\n"
                              "Content-Type: image/dng\r\n"
                              "Content-Disposition: attachment; filename=\"capture.dng\"\r\n"
                              "Content-Length: %u\r\n\r\n",
                              session->captured_data.bytesused);

                    write(session->fd, http_header, len);
                    write(session->fd, session->captured_data.mem, session->captured_data.bytesused);
                } else {
                    const char *response = "HTTP/1.1 500 Internal Server Error\r\n"
                                  "Access-Control-Allow-Origin: *\r\n"
                                  "\r\n"
                                  "Capture or DNG creation failed";

                    write(session->fd, response, strlen(response));
                }
                pthread_mutex_unlock(&session->mtx);
            }
#else
            const char *response = "HTTP/1.1 501 Not Implemented\r\n\r\nCapture requires libcamera support";
            write(session->fd, response, strlen(response));
#endif
        }
    }
    /* ─── /video_controls endpoint ─── */
    else if (strstr(request_buf, "GET /video_controls") == request_buf) {
#ifdef HAVE_LIBCAMERA
        capture_controls_t cc = parse_controls_from_request(request_buf);
        int ret = libcamera_apply_video_controls(session->server->video_src, &cc);
        if (ret == 0) {
            send_json_response(session->fd, 200, "OK",
                               "{\"status\":\"ok\",\"message\":\"Video controls updated\"}");
        } else {
            send_json_response(session->fd, 500, "Internal Server Error",
                               "{\"status\":\"error\",\"message\":\"Failed to apply video controls\"}");
        }
#else
        send_json_response(session->fd, 501, "Not Implemented",
                           "{\"status\":\"error\",\"message\":\"Requires libcamera support\"}");
#endif
    }
    /* ─── /reset_controls endpoint ─── */
    else if (strstr(request_buf, "GET /reset_controls") == request_buf) {
#ifdef HAVE_LIBCAMERA
        int ret = libcamera_reset_controls(session->server->video_src);
        if (ret == 0) {
            send_json_response(session->fd, 200, "OK",
                               "{\"status\":\"ok\",\"message\":\"Controls reset to defaults\"}");
        } else {
            send_json_response(session->fd, 500, "Internal Server Error",
                               "{\"status\":\"error\",\"message\":\"Failed to reset controls\"}");
        }
#else
        send_json_response(session->fd, 501, "Not Implemented",
                           "{\"status\":\"error\",\"message\":\"Requires libcamera support\"}");
#endif
    }
    else {
        const char *response = "HTTP/1.1 404 Not Found\r\n\r\n";
        write(session->fd, response, strlen(response));
    }

cleanup:
    close(session->fd);
    if (session->captured_data.mem) free(session->captured_data.mem);
    pthread_mutex_destroy(&session->mtx);
    pthread_cond_destroy(&session->cond);
    free(session);
    return NULL;
}


static void *http_server_thread(void *arg) {
    struct http_server *server = (struct http_server *)arg;
    while (server->running) {
        int client_fd = accept(server->listen_fd, NULL, NULL);
        if (client_fd < 0) continue;
        struct http_client_session *session = (struct http_client_session*)malloc(sizeof(*session));
        if (!session) {
            close(client_fd);
            continue;
        }
        memset(session, 0, sizeof(*session));
        session->fd = client_fd;
        session->server = server;
        pthread_mutex_init(&session->mtx, NULL);
        pthread_cond_init(&session->cond, NULL);
        if (pthread_create(&session->thread, NULL, client_thread_func, session) != 0) {
            close(client_fd);
            free(session);
        }
        pthread_detach(session->thread);
    }
    return NULL;
}

struct http_server *http_capture_new(int port, struct video_source *video_src) {
    struct http_server *server = (struct http_server*)calloc(1, sizeof(*server));
    if (!server) return NULL;
    
    server->video_src = video_src;

#ifdef HAVE_LIBCAMERA
    server->still_src = libcamera_get_still_source(video_src);
#else
    server->still_src = NULL;
    (void)video_src; // Suppress unused parameter warning
#endif
    
    server->running = true;
    server->listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server->listen_fd < 0) {
        free(server);
        return NULL;
    }
    int opt = 1;
    setsockopt(server->listen_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    struct sockaddr_in serv_addr = {0};
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    serv_addr.sin_port = htons(port);
    if (bind(server->listen_fd, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) < 0 ||
        listen(server->listen_fd, 10) < 0) {
        close(server->listen_fd);
        free(server);
        return NULL;
    }
    if (pthread_create(&server->server_thread, NULL, http_server_thread, server) != 0) {
        close(server->listen_fd);
        free(server);
        return NULL;
    }
    return server;
}

void http_capture_destroy(struct http_server *server) {
    if (!server) return;
    server->running = false;
    shutdown(server->listen_fd, SHUT_RDWR);
    close(server->listen_fd);
    pthread_join(server->server_thread, NULL);
    free(server);
}