/*
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * An HTTP server that serves a complete DNG file generated by libcamera's
 * own DNGWriter. This C file is now just a transport layer.
 *
 * Copyright (C) 2025 Yasin Tunçer
 */

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

#include "config.h"
#include "capture.h"
#include "still-source.h"
#include "video-source.h"

#ifdef HAVE_LIBCAMERA
// libcamera C++ interface
extern struct still_source *libcamera_get_still_source(struct video_source *s);
extern void libcamera_still_source_set_callback(struct still_source *ssrc,
                                                void (*cb)(void *, struct still_buffer *),
                                                void *data);
#endif

// Forward declarations
static void *client_thread_func(void *arg);
static void *http_server_thread(void *arg);
static void still_capture_ready_cb(void *data, struct still_buffer *buffer);

// Callback to receive the final DNG data from the C++ side.
static void still_capture_ready_cb(void *data, struct still_buffer *buffer_from_camera) {
    struct http_client_session *session = (struct http_client_session *)data;

    pthread_mutex_lock(&session->mtx);
    session->captured_data.mem = NULL;
    session->captured_data.error = true;

    if (buffer_from_camera && !buffer_from_camera->error && buffer_from_camera->mem && buffer_from_camera->bytesused > 0) {
        session->captured_data.mem = malloc(buffer_from_camera->bytesused);
        if (session->captured_data.mem) {
            memcpy(session->captured_data.mem, buffer_from_camera->mem, buffer_from_camera->bytesused);

            session->captured_data.bytesused = buffer_from_camera->bytesused;
            session->captured_data.timestamp = buffer_from_camera->timestamp;
            session->captured_data.error = false;
        } else {
            fprintf(stderr, "İstemci DNG arabelleği için bellek ayrılamadı\n");
        }
    }

    session->capture_complete = true;
    pthread_cond_signal(&session->cond);
    pthread_mutex_unlock(&session->mtx);
}

// Thread to handle a client.
static void *client_thread_func(void *arg) {
    struct http_client_session *session = (struct http_client_session *)arg;
    char request_buf[2048] = {0};

    if (read(session->fd, request_buf, sizeof(request_buf) - 1) <= 0) {
        goto cleanup;
    }

    if (strstr(request_buf, "GET /capture") == request_buf) {
        if (!session->server->still_src) {
            const char *response = "HTTP/1.1 503 Service Unavailable\r\n\r\n";
            write(session->fd, response, strlen(response));
        } else {
#ifdef HAVE_LIBCAMERA
            libcamera_still_source_set_callback(session->server->still_src, still_capture_ready_cb, session);
            if (still_source_capture(session->server->still_src) < 0) {
                const char *response = "HTTP/1.1 500 Internal Server Error\r\n\r\nCapture trigger failed";
                write(session->fd, response, strlen(response));
            } else {
                pthread_mutex_lock(&session->mtx);
                while (!session->capture_complete) {
                    pthread_cond_wait(&session->cond, &session->mtx);
                }
                
                if (session->captured_data.mem && !session->captured_data.error) {
                    char http_header[256];
                    int len = snprintf(http_header, sizeof(http_header),
                                       "HTTP/1.1 200 OK\r\n"
                                       "Content-Type: image/dng\r\n"
                                       "Content-Disposition: attachment; filename=\"capture.dng\"\r\n"
                                       "Content-Length: %u\r\n\r\n",
                                       session->captured_data.bytesused);

                    write(session->fd, http_header, len);
                    write(session->fd, session->captured_data.mem, session->captured_data.bytesused);
                } else {
                    const char *response = "HTTP/1.1 500 Internal Server Error\r\n\r\nCapture or DNG creation failed";
                    write(session->fd, response, strlen(response));
                }
                pthread_mutex_unlock(&session->mtx);
            }
#else
            const char *response = "HTTP/1.1 501 Not Implemented\r\n\r\nCapture requires libcamera support";
            write(session->fd, response, strlen(response));
#endif
        }
    } else {
        const char *response = "HTTP/1.1 404 Not Found\r\n\r\n";
        write(session->fd, response, strlen(response));
    }

cleanup:
    close(session->fd);
    if (session->captured_data.mem) free(session->captured_data.mem);
    pthread_mutex_destroy(&session->mtx);
    pthread_cond_destroy(&session->cond);
    free(session);
    return NULL;
}


static void *http_server_thread(void *arg) {
    struct http_server *server = (struct http_server *)arg;
    while (server->running) {
        int client_fd = accept(server->listen_fd, NULL, NULL);
        if (client_fd < 0) continue;
        struct http_client_session *session = (struct http_client_session*)malloc(sizeof(*session));
        if (!session) {
            close(client_fd);
            continue;
        }
        memset(session, 0, sizeof(*session));
        session->fd = client_fd;
        session->server = server;
        pthread_mutex_init(&session->mtx, NULL);
        pthread_cond_init(&session->cond, NULL);
        if (pthread_create(&session->thread, NULL, client_thread_func, session) != 0) {
            close(client_fd);
            free(session);
        }
        pthread_detach(session->thread);
    }
    return NULL;
}

struct http_server *http_capture_new(int port, struct video_source *video_src) {
    struct http_server *server = (struct http_server*)calloc(1, sizeof(*server));
    if (!server) return NULL;
    
#ifdef HAVE_LIBCAMERA
    server->still_src = libcamera_get_still_source(video_src);
#else
    server->still_src = NULL;
    (void)video_src; // Suppress unused parameter warning
#endif
    
    server->running = true;
    server->listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server->listen_fd < 0) {
        free(server);
        return NULL;
    }
    int opt = 1;
    setsockopt(server->listen_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    struct sockaddr_in serv_addr = {0};
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    serv_addr.sin_port = htons(port);
    if (bind(server->listen_fd, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) < 0 ||
        listen(server->listen_fd, 10) < 0) {
        close(server->listen_fd);
        free(server);
        return NULL;
    }
    if (pthread_create(&server->server_thread, NULL, http_server_thread, server) != 0) {
        close(server->listen_fd);
        free(server);
        return NULL;
    }
    return server;
}

void http_capture_destroy(struct http_server *server) {
    if (!server) return;
    server->running = false;
    shutdown(server->listen_fd, SHUT_RDWR);
    close(server->listen_fd);
    pthread_join(server->server_thread, NULL);
    free(server);
}
